ghiro-pg:
  image: postgres:9.5
  container_name: ghiro-pg
  net: "host"
  environment:
    - POSTGRES_USER=ghiro
    - POSTGRES_DB=ghiro
    - POSTGRES_PASSWORD==ghiromanager
  ports:
    - "5432:5432"

ghiro-mongo:
  image: mongo:3.2
  container_name: ghiro-mongo
  net: "host"
  ports:
    - "27017:27017"

ghiro:
  # Set build to "." to build the project in the local directory.
  build: .
  container_name: ghiro
  links:
    - "ghiro-pg"
  ports:
    - "80:80"
  net: "host"
