ghiro-mysql:
  image: mysql:5.7
  container_name: ghiro-mysql
  net: "host"
  environment:
    - MYSQL_ROOT_PASSWORD=ghiromanager
  ports:
    - "3306:3306"

ghiro-mongo:
  image: mongo:3.2
  container_name: ghiro-mongo
  net: "host"
  ports:
    - "27017:27017"

ghiro:
  # Set build to "." to build the project in the local directory.
  build: .
  ports:
    - "80:80"
  net: "host"


